import { useState } from 'react'
import type { PricePoint } from '../types/admin.types'
import { formatCurrency, formatDate, formatNumber } from '../adminUi'

export function PriceTrendChart({ points }: { points: PricePoint[] }) {
  const [active, setActive] = useState<number | null>(null)
  if (points.length < 2) return <p className="rounded-lg bg-panel-alt p-5 text-sm text-ink-soft">Grafik akan tampil setelah tersedia transaksi pada sedikitnya dua tanggal.</p>
  const values = points.map((point) => Number(point.weighted_average_price)); const min = Math.min(...values); const max = Math.max(...values); const span = Math.max(max - min, 1)
  const coordinates = points.map((point, index) => ({ x: 26 + index * (548 / Math.max(points.length - 1, 1)), y: 164 - ((Number(point.weighted_average_price) - min) / span) * 126 }))
  return <div><div className="relative overflow-x-auto" aria-label="Grafik tren harga rata-rata tertimbang"><svg viewBox="0 0 600 190" className="h-auto min-w-140" role="img"><title>Tren harga rata-rata tertimbang</title><line x1="26" y1="164" x2="574" y2="164" stroke="#e1e5e2" /><polyline fill="none" stroke="#0e5c56" strokeWidth="2" points={coordinates.map((point) => `${point.x},${point.y}`).join(' ')} />{coordinates.map((point, index) => <g key={points[index].date} onMouseEnter={() => setActive(index)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(index)} onBlur={() => setActive(null)} tabIndex={0} role="button" aria-label={`${formatDate(points[index].date)}, ${formatCurrency(points[index].weighted_average_price)}`}><circle cx={point.x} cy={point.y} r="8" fill="white" stroke="#0e5c56" strokeWidth="3" /><circle cx={point.x} cy={point.y} r="15" fill="transparent" />{active === index && <g><rect x={Math.min(Math.max(point.x - 70, 5), 455)} y={Math.max(point.y - 55, 4)} width="140" height="42" rx="6" fill="#082e2b" /><text x={Math.min(Math.max(point.x, 75), 525)} y={Math.max(point.y - 38, 21)} textAnchor="middle" fill="white" fontSize="10">{formatDate(points[index].date)}</text><text x={Math.min(Math.max(point.x, 75), 525)} y={Math.max(point.y - 23, 36)} textAnchor="middle" fill="white" fontSize="10" fontWeight="700">{formatCurrency(points[index].weighted_average_price)}</text></g>}</g>)}</svg></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-120 text-left text-xs"><thead className="text-ink-soft"><tr><th className="py-2">Tanggal</th><th>Harga Tertimbang</th><th>Volume</th><th>Transaksi</th></tr></thead><tbody>{points.map((point) => <tr key={point.date} className="border-t border-line"><td className="py-2">{formatDate(point.date)}</td><td>{formatCurrency(point.weighted_average_price)}</td><td>{formatNumber(point.volume_kg)} kg</td><td>{point.transaction_count}</td></tr>)}</tbody></table></div></div>
}
