import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, CalendarDays, Camera, Check, LoaderCircle, MapPin, Pencil, Sprout, Upload } from 'lucide-react'
import { cloneElement, useState, type ReactElement, type ReactNode } from 'react'
import { useForm, useWatch } from 'react-hook-form'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { ConfirmDialog } from '../../../components/ConfirmDialog'
import { UnsavedChangesDialog } from '../../../components/UnsavedChangesDialog'
import { getApiError } from '../../../lib/utils'
import { useBuyerLocations, useFishSizes } from '../../buyer/hooks/useBuyerDemands'
import type { FishSize } from '../../buyer/types/buyerDemand.types'
import { useFarmerHarvestPlans, useSaveFarmerHarvestPlan } from '../hooks/useFarmerHarvestPlans'
import { farmerHarvestPlanSchema, type FarmerHarvestPlanForm } from '../schemas/farmerHarvestPlanSchema'
import type { FarmerHarvestPlan, FarmerHarvestPlanInput } from '../types/farmerHarvestPlan.types'

const today = () => { const date = new Date(); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 10) }
const fishHint = (size: FishSize) => size.min_weight_gram && size.max_weight_gram ? `${Math.floor(1000 / Number(size.max_weight_gram))}-${Math.round(1000 / Number(size.min_weight_gram))} ekor/kg` : 'Panduan belum tersedia'
const formatNumber = (value: string | number) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 }).format(Number(value))
const formatDate = (value: string) => new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`))

const defaults = (): FarmerHarvestPlanForm => ({ pond_name: '', location_id: 0, fish_size_id: 0, estimated_volume_kg: 0, harvest_date: today(), asking_price_per_kg: '', pond_address: '', notes: '', photo: null })

export function FarmerHarvestPlansPage({ editingPlan }: { editingPlan?: FarmerHarvestPlan }) {
  const navigate = useNavigate()
  const location = useLocation()
  const editing = editingPlan ?? null
  const [saved, setSaved] = useState(false)
  const plans = useFarmerHarvestPlans(!editing); const sizes = useFishSizes(); const locations = useBuyerLocations(); const save = useSaveFarmerHarvestPlan()
  const [review, setReview] = useState<FarmerHarvestPlanInput | null>(null); const [message, setMessage] = useState<string>(location.state?.message ?? ''); const [formError, setFormError] = useState('')

  const { register, handleSubmit, control, reset, setValue, setError, formState: { errors, isDirty } } = useForm<FarmerHarvestPlanForm>({ resolver: zodResolver(farmerHarvestPlanSchema), defaultValues: editing ? { pond_name: editing.pond_name, location_id: editing.location.id, fish_size_id: editing.fish_size.id, estimated_volume_kg: Number(editing.estimated_volume_kg), harvest_date: editing.harvest_date, asking_price_per_kg: editing.asking_price_per_kg ? Number(editing.asking_price_per_kg) : '', pond_address: editing.pond_address ?? '', notes: editing.notes ?? '', photo: null } : defaults() })
  const selectedSize = useWatch({ control, name: 'fish_size_id' }); const selectedPhoto = useWatch({ control, name: 'photo' })

  const payload = (value: FarmerHarvestPlanForm): FarmerHarvestPlanInput => ({ ...value, asking_price_per_kg: value.asking_price_per_kg === '' ? null : value.asking_price_per_kg, pond_address: value.pond_address || null, notes: value.notes || null })
  const submit = handleSubmit((value) => { setFormError(''); setMessage(''); const data = payload(value); if (editing) setReview(data); else persist(data) })
  const persist = async (data: FarmerHarvestPlanInput) => { try { const result = await save.mutateAsync({ id: editing?.id ?? null, payload: data }); setMessage(result.message); setReview(null); reset(defaults()); if (editing) setSaved(true) } catch (failure) { const apiError = getApiError(failure, 'Rencana panen belum dapat disimpan.'); const fields = ['pond_name', 'location_id', 'fish_size_id', 'estimated_volume_kg', 'harvest_date', 'asking_price_per_kg', 'pond_address', 'notes', 'photo'] as const; let hasFieldError = false; Object.entries(apiError.errors).forEach(([field, messages]) => { if (fields.includes(field as typeof fields[number])) { hasFieldError = true; setError(field as typeof fields[number], { message: messages[0] }) } }); if (!hasFieldError) setFormError(apiError.message); setReview(null) } }
  const edit = (plan: FarmerHarvestPlan) => navigate(`/app/farmer/rencana-panen/${plan.id}/ubah`)

  if (saved) return <Navigate to="/app/farmer/rencana-panen" replace state={{ message }} />

  return <div className={`mx-auto w-full text-ink ${editing ? 'max-w-2xl' : 'max-w-7xl'}`}>
    <header>{editing ? <Link className="mb-4 inline-flex min-h-9 items-center gap-2 text-xs font-semibold text-tide" to="/app/farmer/rencana-panen"><ArrowLeft size={14} /> Kembali ke Rencana Panen</Link> : <span className="text-xs font-semibold text-tide">Kelola Pasokan</span>}<h1 className="mt-1 text-2xl font-bold md:text-3xl">{editing ? 'Ubah Detail Rencana Panen' : 'Rencana Panen Saya'}</h1><p className="mt-1 text-sm text-ink-soft">{editing ? 'Perbarui informasi rencana panen tambak Anda.' : 'Catat estimasi panen tambak Anda agar pembeli dapat menemukan pasokan lebih awal.'}</p></header>
    <div className={`mt-6 grid items-start gap-5 ${editing ? '' : 'lg:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]'}`}>
      <section className="rounded-xl border border-line bg-white p-5 shadow-sm md:p-6">
        {!editing && <div className="flex items-center gap-2 border-b border-line pb-4"><span className="grid size-8 place-items-center rounded-md bg-success-soft text-tide"><Sprout size={17} /></span><h2 className="font-bold">Rencana Panen Baru</h2></div>}
        <form className="mt-5 grid gap-4" onSubmit={submit} noValidate>
          {message && <p role="status" className="rounded-lg bg-success-soft p-3 text-sm text-success">{message}</p>}{formError && <p role="alert" className="rounded-lg bg-danger-soft p-3 text-sm text-danger">{formError}</p>}
          <Field label="Nama Tambak / Kolam" error={errors.pond_name?.message}><input placeholder="Contoh: Tambak Barokah" {...register('pond_name')} /></Field>
          <Field label="Kecamatan / Lokasi Tambak" error={errors.location_id?.message}><select disabled={locations.isLoading || locations.isError} {...register('location_id')}><option value={0}>Pilih kecamatan tambak</option>{locations.data?.map((location) => <option key={location.id} value={location.id}>Kecamatan {location.name}</option>)}</select></Field>
          <fieldset><legend className="mb-2 text-xs font-semibold">Ukuran Ikan</legend><div className="grid grid-cols-1 gap-2 sm:grid-cols-3">{sizes.data?.map((size) => <label key={size.id} className={`cursor-pointer rounded-lg border p-3 text-center transition-all hover:border-tide ${Number(selectedSize) === size.id ? 'border-tide bg-success-soft ring-1 ring-tide/20' : 'border-line bg-panel-alt'}`}><input type="radio" value={size.id} className="sr-only" {...register('fish_size_id')} /><strong className="block text-xs">{size.name}</strong><small className="mt-1 block text-[10px] text-ink-soft">{fishHint(size)}</small></label>)}</div>{errors.fish_size_id && <p className="mt-1 text-xs text-danger">{errors.fish_size_id.message}</p>}</fieldset>
          <div className="grid gap-4 sm:grid-cols-2"><Field label="Perkiraan Jumlah (kg)" error={errors.estimated_volume_kg?.message}><input type="number" min="0.01" step="0.01" {...register('estimated_volume_kg')} /></Field><Field label="Perkiraan Tanggal Panen" error={errors.harvest_date?.message}><input type="date" min={today()} {...register('harvest_date')} /></Field></div>
          <Field label="Harga Harapan / Acuan (per kg) — opsional" error={errors.asking_price_per_kg?.message}><input type="number" min="1" step="1" placeholder="Contoh: 32000" {...register('asking_price_per_kg')} /></Field>
          <Field label="Alamat Tambak — opsional" error={errors.pond_address?.message}><textarea rows={2} placeholder="Detail lokasi tambak" {...register('pond_address')} /></Field>
          <div><label htmlFor="harvest-photo" className="mb-2 block text-xs font-semibold">Foto Kondisi Tambak / Ikan <span className="font-normal text-ink-soft">— opsional</span></label><label className="flex min-h-20 cursor-pointer items-center gap-3 rounded-lg border border-dashed border-line bg-panel-alt p-4 transition-colors hover:border-tide hover:bg-success-soft"><span className="grid size-10 place-items-center rounded-md bg-white text-tide"><Camera size={19} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{selectedPhoto?.name ?? (editing?.photo_url ? 'Pilih foto baru untuk mengganti foto lama' : 'Pilih foto atau seret berkas ke sini')}</strong><small className="text-[10px] text-ink-soft">JPG atau PNG, maksimal 5 MB</small></span><Upload size={17} className="text-ink-soft" /><input id="harvest-photo" type="file" accept="image/jpeg,image/png" className="sr-only" onChange={(event) => setValue('photo', event.target.files?.[0] ?? null, { shouldDirty: true, shouldValidate: true })} /></label>{errors.photo && <p className="mt-1 text-xs text-danger">{errors.photo.message}</p>}</div>
          <div className="flex justify-end gap-2 border-t border-line pt-4">{editing && <Link className="inline-flex min-h-11 items-center rounded-md border border-line px-4 text-sm font-semibold text-ink" to="/app/farmer/rencana-panen">Batal</Link>}<button type="submit" disabled={save.isPending} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-md bg-tide px-4 text-sm font-semibold text-white shadow-sm transition-all enabled:hover:bg-tide-dark enabled:hover:shadow-md enabled:active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50">{save.isPending ? <LoaderCircle className="animate-spin" size={17} /> : <Check size={17} />}{editing ? 'Simpan Perubahan' : 'Simpan Rencana'}</button></div>
        </form>
      </section>
      {!editing && <aside><div className="flex items-center justify-between"><h2 className="font-bold">Rencana Aktif Anda</h2>{plans.data && <span className="rounded-full bg-success-soft px-2 py-1 text-[10px] font-semibold text-success">{plans.data.meta.total} tersedia</span>}</div>
        <div className="mt-3 grid gap-3">{plans.isLoading && <State><LoaderCircle className="animate-spin" size={18} /> Memuat rencana...</State>}{plans.isError && <State>Rencana gagal dimuat. <button type="button" onClick={() => plans.refetch()} className="font-bold text-tide">Coba lagi</button></State>}{plans.data?.data.length === 0 && <State>Belum ada rencana aktif. Isi form untuk membuat rencana pertama.</State>}{plans.data?.data.map((plan) => <HarvestCard key={plan.id} plan={plan} onEdit={() => edit(plan)} />)}</div>
      </aside>}
    </div>
    <ConfirmDialog open={review !== null} title="Simpan perubahan rencana?" description="Perubahan akan memperbarui informasi pasokan yang dilihat calon pembeli." confirmLabel="Ya, Simpan" pending={save.isPending} onCancel={() => setReview(null)} onConfirm={() => review && persist(review)} />
    <UnsavedChangesDialog when={isDirty && !save.isPending && review === null} />
  </div>
}

function Field({ label, error, children }: { label: string; error?: string; children: ReactElement<{ className?: string; 'aria-invalid'?: boolean }> }) { const child = cloneElement(children, { 'aria-invalid': Boolean(error), className: `min-h-10 w-full rounded-md border bg-white px-3 py-2 text-sm outline-none transition-colors focus:border-tide focus:ring-2 focus:ring-tide/10 ${error ? 'border-danger' : 'border-line'} ${children.props.className ?? ''}` }); return <label className="block text-xs font-semibold">{label}<span className="mt-1 block">{child}</span>{error && <span className="mt-1 block text-[11px] font-normal text-danger">{error}</span>}</label> }
function State({ children }: { children: ReactNode }) { return <div className="flex min-h-28 items-center justify-center gap-2 rounded-xl border border-line bg-white p-5 text-center text-xs text-ink-soft">{children}</div> }
function HarvestCard({ plan, onEdit }: { plan: FarmerHarvestPlan; onEdit: () => void }) { const days = Math.ceil((new Date(`${plan.harvest_date}T00:00:00`).getTime() - new Date(`${today()}T00:00:00`).getTime()) / 86_400_000); return <article className="overflow-hidden rounded-xl border border-line bg-white shadow-sm">{plan.photo_url && <img src={plan.photo_url} alt={`Kondisi ${plan.pond_name}`} className="h-32 w-full object-cover" />}<div className="p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[9px] font-semibold uppercase tracking-wide text-ink-soft">Nama Tambak</span><h3 className="mt-1 font-bold">{plan.pond_name}</h3><p className="mt-1 flex items-center gap-1 text-[11px] text-ink-soft"><MapPin size={12} /> Kec. {plan.location.name}</p></div><span className="rounded-full bg-success-soft px-2 py-1 text-[9px] font-bold text-success">Tersedia</span></div><div className="mt-4 rounded-lg bg-success-soft p-3"><p className="flex items-center justify-between text-[10px] text-ink-soft"><span>Rencana Panen</span><strong className="text-success">{days <= 0 ? 'Siap Panen' : `H-${days}`}</strong></p><p className="mt-1 flex items-center gap-1 text-xs font-bold"><CalendarDays size={13} /> {formatDate(plan.harvest_date)}</p></div><dl className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div className="rounded-md bg-panel-alt p-2"><dt className="text-ink-soft">Volume</dt><dd className="mt-1 font-bold">{formatNumber(plan.estimated_volume_kg)} kg</dd></div><div className="rounded-md bg-panel-alt p-2"><dt className="text-ink-soft">Harga harapan</dt><dd className="mt-1 font-bold">{plan.asking_price_per_kg ? `Rp${formatNumber(plan.asking_price_per_kg)}/kg` : 'Diskusikan'}</dd></div></dl><button type="button" onClick={onEdit} className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-md bg-tide px-4 text-xs font-semibold text-white transition-colors hover:bg-tide-dark"><Pencil size={14} /> Ubah Detail</button></div></article> }
